[tool.isort]
force_single_line = true  # one import per line
lines_after_imports = 2  # blank spaces after import section

[tool.coverage.report]
exclude_lines = [
    "enum.IntEnum",
    "except ImportError:",
    "globals().update",
    "if BSD",
    "if FREEBSD",
    "if LINUX",
    "if LITTLE_ENDIAN:",
    "if MACOS",
    "if NETBSD",
    "if OPENBSD",
    "if PY3:",
    "if SUNOS",
    "if WINDOWS",
    "if _WINDOWS:",
    "if __name__ == .__main__.:",
    "if enum is None:",
    "if enum is not None:",
    "if has_enums:",
    "if ppid_map is None:",
    "if sys.platform.startswith",
    "import enum",
    "pragma: no cover",
    "raise NotImplementedError",
]
omit = [
    "psutil/_compat.py",
    "psutil/tests/*",
    "setup.py",
]

[tool.pylint.messages_control]
# Important ones:
# undefined-all-variable, invalid-envvar-default, reimported, raising-format-tuple, simplifiable-if-expression, useless-object-inheritance
disable = [
    "broad-except",  # except Exception:
    "consider-using-dict-comprehension",
    "consider-using-f-string",
    "consider-using-set-comprehension",
    "consider-using-with",
    "disallowed-name",
    "fixme",
    "global-statement",
    "import-error",
    "import-outside-toplevel",
    "inconsistent-return-statements",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "no-else-raise",
    "no-else-return",
    "protected-access",
    "raise-missing-from",
    "redefined-builtin",
    "super-with-arguments",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    "ungrouped-imports",
    "unspecified-encoding",
    "wrong-import-position",
]

[tool.rstcheck]
ignore_messages = [
    "Duplicate explicit target name",
    "Duplicate implicit target name",
    "Hyperlink target \".*?\" is not referenced",
]

[tool.tomlsort]
in_place = true
no_sort_tables = true
sort_inline_arrays = true
spaces_before_inline_comment = 2
spaces_indent_inline_array = 4
trailing_comma_inline_array = true

[tool.cibuildwheel]
skip = ["*-musllinux*", "pp*"]
test-command = [
    "env PYTHONWARNINGS=always PYTHONUNBUFFERED=1 PSUTIL_DEBUG=1 PSUTIL_SCRIPTS_DIR={project}/scripts python {project}/psutil/tests/runner.py",
    "env PYTHONWARNINGS=always PYTHONUNBUFFERED=1 PSUTIL_DEBUG=1 PSUTIL_SCRIPTS_DIR={project}/scripts python {project}/psutil/tests/test_memleaks.py",
]
test-extras = "test"

[tool.cibuildwheel.macos]
archs = ["arm64", "x86_64"]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=43", "wheel"]
