name: Build wheels

on: [push, pull_request]

jobs:
  wheel:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version:
          - 2.7
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    env:
      CIBW_TEST_COMMAND: python -u -Wa {project}/psutil/tests/runner.py
      CIBW_TEST_COMMAND_MACOS: LC_ALL='en_US.utf8' python -Wa {project}/psutil/tests/runner.py
      CIBW_TEST_EXTRAS: test
      CIBW_SKIP: pp*
    steps:
    - uses: actions/checkout@v1
    # - uses: actions/setup-python@v1
    - uses: actions/setup-python@v2.1.1
      name: Install Python 3.7
      with:
        python-version: '3.7'

    - name: Install Visual C++ for Python 2.7
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install vcpython27 -f -y

    - name: Install cibuildwheel
      run: pip install cibuildwheel==1.4.1

    - name: Build wheels
      run: cibuildwheel .

    - name: Upload wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: wheelhouse

    - name: Create tar.gz
      run: |
        make generate-manifest
        python setup.py sdist
        mv dist/psutil*.tar.gz wheelhouse/

    - name: Print hashes
      run: python scripts/internal/md5sum.py wheelhouse/*
