name: FreeBSD

on: [push, pull_request]

jobs:
  test-freebsd:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      id: test
      uses: vmactions/freebsd-vm@v0.0.8
      with:
        usesh: true
        prepare: pkg install -y gcc python3
        run: |
          python3 -m pip install --user setuptools
          make clean
          make install
          make test
          make test-memleaks
