name: FreeBSD

on: [push, pull_request]

jobs:
  test-freebsd:
    runs-on: macos-latest
    name: Test run
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Install & run
      id: test
      uses: vmactions/freebsd-vm@v0.0.8
      with:
        usesh: true
        prepare: pkg install -y gcc python3
        run: |
          pwd
          ls -lah
          make install-pip
          python3 -m pip install setuptools
          python3 setup.py install
          python3 -Wa psutil/tests/runner.py
