name: FreeBSD test

on: [push, pull_request]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: A job to run test FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Install & run
      id: test
      uses: vmactions/freebsd-vm@v0.0.8
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y gcc python3
        run: |
          pwd
          ls -lah
          python3 setup.py install
          python3 -Wa psutil/psutil/tests/runner.py
